### ISSUE TITLE
public domain the function?

### ISSUE THREAD

**Issue by tedder** [tlastowka/calculate_multipart_etag#1]
Hi tlastowka, I want to use your main function in an [Ansible](http://github.com/ansible/) module. It's mostly licensed GPL; can you make this public domain so I don't have to worry about licensing it?

**Comment by tlastowka** [comment]
It's already under the GPL. It sounds like your thing is too.  Is that what
you are asking?

**Comment by tedder** [comment]
Since I'm not using it as an external library I'm worried that it will add hassle to the pull request that will put code into Ansible. Maybe I can just include you as a contributor, but since it's more of a snippet than a large amount of code, I was hoping you'd make it public domain (I mean, freely distributable, removing the license).
