### ISSUE TITLE
please do not use the script, it crash the server

### ISSUE THREAD

**Issue by robertchen** [tlastowka/calculate_multipart_etag#2]
for a 3G file, it crashed the server with 100% CPU and no responding for ssh session to come back for killing the job. 

Received keyboard interrupt, quitting threads
Exception KeyboardInterrupt in <module 'threading' from '/usr/lib64/python2.7/threading.pyc'> ignored

**Comment by tlastowka** [comment]
Generating the etag locally requires it to generate a hash of each chunk of the file.  That's how amazon designed the algorithm.  A 3 gig file is going to take a long time and a lot of resources to do that.

**Comment by VietTralala** [comment]
My linux system also froze, but this was due to the fact, that I used a wrong (too small) chunk_size. Keep in mind that the chunk_size has to by provided in bytes. Maybe this fixed the problem!
